Update CI to support mono repo

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -19,8 +19,8 @@ jobs:
         run: |
           poetry export --output temp-requirements.txt -vvv
 
-          if ! cmp -s "requirements.txt" "temp-requirements.txt"; then
-            echo "::error file=requirements.txt,title=Requirements out of date!::Run 'poetry export --output requirements.txt'"
+          if ! cmp -s "thallium-backend/requirements.txt" "temp-requirements.txt"; then
+            echo "::error file=requirements.txt,title=Requirements out of date!::Run 'make lock'"
             exit 1
           fi
 
